### ISSUE TITLE
read/write permissions

### ISSUE THREAD

**Issue by agadek** [AsavarTzeth/docker-sftp#4]
Hey,
how to configure custom user with write privilage to make uploding files allowed for user?

thanks in advance AG

**Comment by AsavarTzeth** [comment]
Okay let me just quickly state that I am not as interested in Docker as I used to be (for various good reasons). That being said I have put a lot of work into this specific container and I don't plan to throw all that away.

What I never managed to finish was my much improved user guide, which might help you. If you are interested, switch to the beta branch in the github repo. I never pushed it to master for some reason.

As for your question. You need to make sure the UID of your sftp user (inside the container) matches where you store your data (host, container, whatever you choose).

To better explain this I would need more information about your setup (what docker commands you ran). I have provided the easy to use `SFTP_USER` and `SFTP_UID` environment variables to make it as simple as possible to not have this issue.

**Comment by agadek** [comment]
ok, thx 

i've solved this problem. linux file permission was always mistery for me ;-)

**Comment by AsavarTzeth** [comment]
Well it's not Linux file permissions, but Unix permissions. Those are pretty much the way every single system in the world works, except for Windows, which only uses file system specific ACLs. Linux & Posix systems have ACLs as well, but it is not as widely used, mainly because Unix permissions are simpler and most often gets the job done.

If you really are interested I recommend you look up Unix permissions on Wikipedia or something. I too were once confused about them, but it helped me a lot. If anything what confused me the longest was how the octal values worked, but that is because I am weak in mathematics.

But that is enough ramblings from me :) I am glad you found your solution. Closing this.
